[package]
name = "ncut-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "ncut"
path = "src/main.rs"

[dependencies]
ncut-core.workspace = true
anyhow.workspace = true
tokio.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive", "env"] }
